version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: DocumentEditor
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.4.3
    container_name: redis-server-2
    restart: no
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "redis"]

volumes:
  mongodb_data:
